logging:
  level:
    root: INFO
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
    '[me.soknight.studying.institute]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

spring:
  application:
    name: Instutute

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

  main:
    banner-mode: off

  sql:
    init:
      mode: always

  web:
    locale: ru_RU