logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[me.soknight.studying.calculator]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

spring:
  application:
    name: Calculator

  main:
    banner-mode: off